qubole/rubix

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java

Extend stats to show number of requests served from cache and from remote

Extend stats to show number of requests

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/DiskMonitorService.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/utils/DiskUtils.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java

This service is responsible to add an entry in cache which denotes the total disk used up.
Only this entry has non-zero weight in the cache and once the weight of this entry comes
close to cache max-weight, evictions would start.
This benefits us over the old approach of aggressive invalidations of cache entries and re-entries
with the size occupied on disk at that time by lowering the amount of work as invalidation are much
fewer now.
Also, the shift towards executing the old approach in new thread had lead to explosion of threads
slowing down the service.

Added DiskMonitor service

---

.gitignore
README.md
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/LocalDataTransferServer.java
rubix-spi/pom.xml
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
rubix-tests/pom.xml
rubix-tests/src/test/java/com/qubole/rubix/tests/DeleteFileVisitor.java
rubix-tests/src/test/java/com/qubole/rubix/tests/TestCachingInputStream.java
rubix-tests/src/test/java/com/qubole/rubix/tests/TestNonLocalReadRequestChain.java

Upgraded thrift from 0.9.0 to 0.9.3. The main motivation is that
0.9.3 can be installed through brew on mac. I tried to upgrade to
thrift 0.10.0 but there were test failures.
Upgrade maven-thrift-plugin to 0.1.11. 0.1.10 is not available anymore
in http://maven.davidtrott.com/repository. 0.1.11 is available in apache
maven repository.
Another improvement is that tests assumed specific directory
structures internal to Qubole. The test directories are now
configured relative to `java.io.tmpdir`.

new:dev: Upgrade thrift & maven-thrift-plugin. Make tests relocatable

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java
rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java
rubix-core/src/test/java/com/qubole/rubix/core/MockCachingFileSystem.java
rubix-tests/src/test/java/com/qubole/rubix/tests/TestCachingInputStream.java

Instead of creating a new instance of FSDataInputStream, we are instantiating it only when we needed.

Lazy loading of FSDataInputStream

---

README.md
assembly/pom.xml
pom.xml
rubix-rpm/pom.xml

Generate RPM with instructions in README. RPM is not generated
in _default_ or _release_ profile. 
The RPM contents are:
```
/usr/lib/rubix/conf
/usr/lib/rubix/lib
/usr/lib/rubix/lib/rubix-bookkeeper-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-core-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-hadoop1-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-hadoop2-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-presto-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-rpm-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/lib/rubix-spi-0.2.12-SNAPSHOT.jar
/usr/lib/rubix/logs 
```
The content will evolve with installation code.

new:usr:Add a new module to generate rpm for rubix

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java

as per guava source code
https://github.com/google/guava/blob/master/guava/src/com/google/common/cache/LocalCache.java#L2623
the weight of individual items needs to be a positive integer to have that item eligible for eviction.

fix: dev: Assigning a non-zero weight for each of the files in the cache to start eviction

---

CONTRIBUTING.md
docs/Makefile
docs/conf.py
docs/contrib/coding.md
docs/contrib/commit.md
docs/contrib/develop.md
docs/contrib/doc.md
docs/contrib/env.md
docs/contrib/index.rst
docs/contrib/issues.md
docs/contrib/pr.md
docs/index.rst
docs/metrics.md
docs/metrics.rst

#130 
Add more details to contribution guide for code, issues, PR and documentation. Also
add a CONTRIBUTING.md. This file will be hyperlinked when some one opens an issue
or PR. Check https://help.github.com/articles/setting-guidelines-for-repository-contributors/. 
Heavily inspired by Discourse Guidelines: https://help.github.com/articles/setting-guidelines-for-repository-contributors/. This commit also makes a minor fix to metrics page.

new:usr:Add more details to Contribution Guide and a markdown file 

---

.gitchangelog.rc
CHANGELOG

Create a new file to hold CHANGELOG. The changelog is generated using gitchangelog. 
The required RC file has been added in this commit as well. Instructions regarding commit 
message formats and to generate the CHANGELOG will be added in a subsequent commit.

chg:usr:Add a CHANGELOG File

---

pom.xml
rubix-bookkeeper/pom.xml
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperServer.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java

- Passed smoke test on Qubole cluster
- Currently verifying that metrics are sent to DogStatsD on Qubole cluster using default config settings (localhost:8125)

Send registered metrics to StatsD via StatsDReporter

---

rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperServer.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestHeartbeatService.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/validation/TestCachingValidator.java

Addressing some issues discovered in the Travis build logs which might be affecting the success of other tests:
- FileValidator trying to validate cache directory with "null" prefix
- Prefix not correctly set for CachingValidator tests

fix: dev: #235: address test issues to try to fix Travis build failures

---

script.sh

`mvn cobertura:cobertura-integration-test` runs the `verify` phase, which includes the `package` phase needed to shade the JARs for tests in later modules. This means that the `bookkeeper` tests should now all pass and report the correct coverage.

fix: dev: #186: use appropriate Cobertura goal to shade jars before testing

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/HeartbeatService.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/FileValidator.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/validation/TestCachingValidator.java

By supplying the same single-threaded executor to both validators, each validator will still be correctly scheduled, but will no longer be running concurrently with another validation.

fix: dev: #243: Schedule validators on same thread to avoid overlap

---

rubix-spi/src/main/java/com/qubole/rubix/spi/CacheUtil.java

The exception occurred because the bks service did not have write privileges over the cache table directories and consequently was not able to create metadata files in the case of Non local reads. 
- Making the cached table directories writable recursively from Cache util
fixes #297

fix: dev: #297: Fix No such file or directory exception in bks logs

---

rubix-core/src/main/java/com/qubole/rubix/core/NonLocalRequestChain.java

- NonLocalRequestChain.getStats() was reporting all requests as remote reads which is wrong. 
- Marking those requests that go to the NonLocalReadRequestChain as nonlocal reads with this change. 
- The rest of the requests that go to the RemoteFetchRequestChain result in data getting downloaded asynchronously in the non-local node, while the requesting node falls back to direct reads, and direct reads stats are not collected.
fixes #300

fix: usr: #300: Modify getStats() in NonLocalRequestChain to report correct Cache Stats

---

.travis.yml

Caching the Maven repository will significantly reduce the amount of log lines generated during CI builds, which will avoid build errors from reaching the maximum log length.

chg: dev: #310: cache Maven repository to reduce generated log lines

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/LocalDataTransferServer.java

In a test program to make 1000 BKS calls via 100 threads, lot of calls failed with "Connection reset" and other Socket Exceptions. It happens because the way we are configuring thrift server, it does not queue up any connection while socket accept() is busy handing over work to a worker thread. This change enables queueing up such connections by setting the queue length to maximum by setting it to Integer.MAX_VALUE (the real limit is implementation specific and not documented anywhere, used Integer.MAX_VALUE to get the maximum queue length).
After this change I could not repro the socket exceptions in my test program even after increasing number of calls and number of threads.

Allow connection backlog for socket accept()

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java
rubix-core/src/main/java/com/qubole/rubix/core/DummyModeCachingInputStream.java
rubix-spi/src/main/java/com/qubole/rubix/spi/BookKeeperFactory.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPool.java
rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPoolPartition.java

- Do not cache Client in CachingInputStream. It is light-weight to open new client now while caching client can lead to deadlock if consumer is moved out of scheduler
- Replace a connection which is being removed due a exception

Fixes to prevent deadlocks with lower connection pool size

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/DownloadRequestContext.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FetchRequest.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloadRequestChain.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloader.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/LocalDataTransferServer.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/RemoteFetchProcessor.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/validation/CachingValidator.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeper.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestFileDownloader.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestRemoteFetchProcessor.java
rubix-client/src/test/java/com/qubole/rubix/client/robotframework/BookKeeperClientRFLibrary.java
rubix-common/src/main/java/com/qubole/rubix/common/utils/DataGen.java
rubix-core/src/main/java/com/qubole/rubix/core/CachedReadRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java
rubix-core/src/main/java/com/qubole/rubix/core/ChainedReadRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/DirectReadRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/NonLocalReadRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/NonLocalRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/ReadRequest.java
rubix-core/src/main/java/com/qubole/rubix/core/ReadRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/RemoteFetchRequestChain.java
rubix-core/src/main/java/com/qubole/rubix/core/RemoteReadRequestChain.java
rubix-core/src/test/java/com/qubole/rubix/core/TestCachedReadRequestChain.java
rubix-core/src/test/java/com/qubole/rubix/core/TestRemoteReadRequestChain.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CommonUtilities.java
rubix-spi/src/main/thrift/bookkeeper.thrift
rubix-tests/src/test/java/com/qubole/rubix/tests/TestNonLocalReadRequestChain.java

Multiple fixes, reviewing by commits will be easier:
- Move ReadRequestChain.call to long type: so that we dont restrict Chains to 2GB download limits
- Make clusterType optional in CacheStatusRequest: this allows any client (like parallel warmup system), without the knowledge of cluster-type, to communicate with bookKeeper as long as bookKeeper has been initialized
- Download from remote in chunks of max 10MB (configurable) during parallel warmup: This fixes heavy memory usage.
- Align readRequests to block boundary: This fixes cases of wrong updates to cache leading to read errors
- Use BookKeeper to create metadata-file instead of doing the work from outside
- Fix Ranges in DownloadRequestContext to be closed-open instead of open-open: This improves merging of ranges
- Avoid redundant …

Fix parallel warmup

---

rubix-bookkeeper/pom.xml
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/utils/DiskUtils.java

it might not be available in embedded mode e.g in case of Presto commons-land is shaded and its namespace is relocated.
Checked other dependencies that are marked `provided` scope. They are safe.

Remove dependency on commons-lang

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java

Filter file system is a common way of wrapping
another file system which allows to unwind raw
file system in a generic way.

Make CachingFileSystem extend FilterFileSystem

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloader.java

In parallel warmup mode file might be gone by the
time Rubix tries to download it. Since this is something
that is expected, it doesn't need to be logged as error.

Reduce logging level for FileNotFoundExceptions

---

docs/index.rst
docs/release/index.rst
docs/release/release_notes/release-0.3.10.rst
docs/release/release_notes/release-0.3.11.rst

This is how main page of docs looks like now:
This is how the release notes page looks like now:

Add release notes in docs

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloadRequestChain.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloader.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/LocalDataTransferServer.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/RemoteFetchProcessor.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java

Tested the changes with parallel warmup enabled/disabled in embedded & non-embedded mode by firing long-running tpcds catalog queries concurrently containing results parquet/orc/text format.

Enable fileSystem cache in rubix

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java

This should prevent errors like https://github.com/prestosql/presto/pull/3987#issuecomment-642225940 when caching data on master is disabled. Cache itself needs to be enabled on master because coordinator needs to know where to schedule splits.

Do not obtain localPath when caching data on master is disabled

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java

FilterFileSystem does initialize embedded
FileSystem as part of initialize method.
Therefore it doesn't need to be initialized again
in CachingFileSystem#initialize.

Initialize embedded FileSystme once

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloader.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/utils/DiskUtils.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeper.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestFileDownloader.java
rubix-client/src/test/java/com/qubole/rubix/client/robotframework/BookKeeperClientRFLibrary.java
rubix-core/src/main/java/com/qubole/rubix/core/utils/DummyClusterManager.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
rubix-spi/src/main/java/com/qubole/rubix/spi/utils/DataSizeUnits.java

fixes #404
Last Block of files is usually not aligned to Block boundary, 1MB. But
we were adding the full weight of Block, 1MB, to the Cache for such blocks.
This lead to over-estimation of Cache size and hence early evictions.
This change limits the max size of file computed by the actual file size.
Also, with this change, the weight of each file in Cache is represent by it's size in KB
instead of MB. Which means we cannot support file > 1TB in size, which is a big
enough.

Fix over-estimation of Cache size

---

rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java

Existing `getFileBlockLocations(Path p, long start, long len)` makes `getFileStatus(p)` to get the fileStatus to pass into `getFileBlockLocations(FileStatus file, long start, long len)` which is unnecessary and causes extra cloud store calls slowing down the split generation

Avoid extra getFileStatus call in listLocatedStatus

---

rubix-build/pom.xml

build will fail in the client using rubix build as jar with duplicate class.
Made similar to presto-shaded module.

shade com.google in build module

---

rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloadRequestChain.java
rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileDownloader.java
rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestFileDownloader.java
rubix-core/src/main/java/com/qubole/rubix/core/ReadRequest.java
rubix-core/src/main/java/com/qubole/rubix/core/ReadRequestChain.java
rubix-core/src/test/java/com/qubole/rubix/core/TestReadRequestChain.java
rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java

Fixes #463 
Main changes:
1. Limit the size of each readRequest in FileDownloadRequestChain to 100MB
2. With the download of each readRequest itself update the metadata instead of existing behavior of downloading all the data in the Chain and then updating metadata
This ensures we will never cross over the configured threshold of disk utilization by 1GB. This crossing over is actually partially handled by only considering 95% of disk space as available, keeping 5% as buffer space for this cross over but in existing warmup scenario we could cross the limit by a much bigger margin.

Minimize error in space usage accounting
