- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
- rubix-bookkeeper/src/main/thrift/bookkeeper.thrift
Created a new method in server which returns Cache statistics (Cache Hit Rate and Miss Rate).
> Method in server to return Cache statistics

- assembly/pom.xml
- assembly/src/main/resources/assemblies/rubix-hadoop2.xml
- pom.xml
- rubix-hadoop2/pom.xml
- rubix-hadoop2/src/main/java/com/qubole/rubix/hadoop2/CachingHadoop2FileSystem.java
- rubix-hadoop2/src/main/java/com/qubole/rubix/hadoop2/Hadoop2ClusterManager.java
- rubix-hadoop2/src/test/java/com/qubole/rubix/hadoop2/TestClusterManager.java
Created a Hadoop2-extension for rubix
> Implement Hadoop-2 extension

- pom.xml
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperConfig.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/MappedByteBufferBitmap.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/utils/ShellExec.java
- rubix-core/src/main/java/com/qubole/rubix/core/CachingConfigHelper.java
- rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java
- rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystemStats.java
- rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java
- rubix-core/src/main/java/com/qubole/rubix/core/ClusterManager.java
- rubix-core/src/main/java/com/qubole/rubix/core/RemoteReadRequestChain.java
- rubix-core/src/test/java/com/qubole/rubix/core/TestCachingInputStream.java
- rubix-hadoop1/src/main/java/com/qubole/rubix/hadoop1/Hadoop1ClusterManager.java
- rubix-hadoop1/src/test/java/com/qubole/rubix/hadoop1/TestClusterManager.java
- rubix-hadoop2/src/main/java/com/qubole/rubix/hadoop2/Hadoop2ClusterManager.java
- rubix-hadoop2/src/test/java/com/qubole/rubix/hadoop2/TestClusterManager.java
- rubix-presto/src/main/java/com/qubole/rubix/presto/PrestoClusterManager.java
- rubix-presto/src/test/java/com/qubole/rubix/presto/TestClusterManager.java
- src/checkstyle/checks.xml
added checkstyle and made corresponding changes
> Add checkstyle

- assembly/pom.xml
- rubix-hadoop2/rubix-hadoop2CM/pom.xml
- rubix-hadoop2/rubix-hadoop2FS/pom.xml
- rubix-spi/pom.xml
Updated versions for hadoop2 and spi
> Version change

- rubix-rpm/pom.xml
- rubix-rpm/src/main/resources/rpm/config/log4j.properties
- rubix-rpm/src/main/resources/rpm/config/log4j_lds.properties
- rubix-rpm/src/main/resources/rpm/init.d/rubix.service
- rubix-rpm/src/main/resources/rpm/scripts/postinst
This commit adds 
* configuration files for bookkeeper and lds. 
* Start/Stop scripts
* Sets up run, log and conf directories.
Tested using rubix-admin on Qubole clusters.
> new:usr:Improve RPM package with configuration and scripts

- .travis.yml
- README.md
- rubix-tests/src/test/java/com/qubole/rubix/tests/TestCachingInputStream.java
- rubix-tests/src/test/java/com/qubole/rubix/tests/TestNonLocalReadRequestChain.java
-add badge to project README to display status of Travis "master" build status
> Travis CI Configuration

- .travis.yml
- README.md
- pom.xml
PR for issue #100 
- integrate Cobertura into Travis build process
- send Cobertura report to Coveralls for coverage statistics
> Integrate Cobertura for code coverage

- pom.xml
- rubix-bookkeeper/pom.xml
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeperServer.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/CoordinatorBookKeeper.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/WorkerBookKeeper.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeper.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperMetrics.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestBookKeeperServer.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestFileDownloader.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestRemoteFetchProcessor.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/TestWorkerBookKeeper.java
- rubix-bookkeeper/src/test/java/com/qubole/rubix/bookkeeper/manager/TestCoordinatorManager.java
- rubix-bookkeeper/src/test/resources/log4j.properties
- rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
- rubix-tests/src/test/java/com/qubole/rubix/tests/TestCachingInputStream.java
- rubix-tests/src/test/java/com/qubole/rubix/tests/TestNonLocalReadRequestChain.java
- Successfully tested on a Qubole cluster
> Fix #158: Add retry logic to HeartbeatService

- rubix-presto/pom.xml
Addressed the httpclient security alert
> Fixed the httpclient version 

- rubix-core/src/main/java/com/qubole/rubix/core/CachingInputStream.java
Daemonized the ReadRequestChain threads
> fix: dev: ISS-334: ReadRequestChain threads got deamonized

- .github/workflows/ci-tests.yml
- Dockerfile
- pom.xml
- rubix-bookkeeper/pom.xml
- rubix-client/pom.xml
- rubix-common/pom.xml
- rubix-common/src/main/java/com/qubole/rubix/common/metrics/BookKeeperMetrics.java
- rubix-common/src/main/java/com/qubole/rubix/common/utils/ClusterUtil.java
- rubix-core/pom.xml
- rubix-hadoop2/pom.xml
- rubix-presto-shaded/pom.xml
- rubix-presto/pom.xml
- rubix-prestosql/pom.xml
- rubix-spi/pom.xml
- rubix-tests/pom.xml
- src/checkstyle/checkstyle_packages.xml
Fixes https://github.com/qubole/rubix/issues/340
> Upgrade to java 8 and guava 26

- rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java
skipCache is path dependant
cacheSkipped is used in getFileBlockLocations with the expectation that it is set in open, but open might not be called
> Remove usage of cacheSkipped

- .gitignore
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/ThrowingEmptyCache.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
> chg: dev: #364: Allow disabling data caching on master

- rubix-spi/src/main/java/com/qubole/rubix/spi/RetryingPooledThriftClient.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPool.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPoolPartition.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/Poolable.java
- rubix-spi/src/test/java/com/qubole/rubix/spi/client/TestPoolingClient.java
1. Fix a connection leak in case of failed connection
2. Ensure a caller always gets a connection if the pool can grow
> Fixes to connection pool

- rubix-core/src/main/java/com/qubole/rubix/core/CachingFileSystem.java
Making CachingFileSystem a FilterFileSystem caused listLocatedStatus
to be delegated to DistributedFileSystem directly (instead of using
default FileSystem#listLocatedStatus) implementation. This caused
produced file statuses to contain remote BlockLocation (instead of
cached ones).
This change overrides listLocatedStatus method so that it returns
cached BlockLocations. Additionally, it does it in iterative fashion
instead of fetching all locations eagerly (as default FileSystem#listLocatedStatus)
implementation does.
> Provide cached locations in FileSystem#listLocatedStatus

- rubix-prestosql/pom.xml
- rubix-prestosql/src/main/java/com/qubole/rubix/prestosql/CachingPrestoAliyunOSSFileSystem.java
https://hadoop.apache.org/docs/current/hadoop-aliyun/tools/hadoop-aliyun/index.html
> Add support for AliyunOSSFileSystem

- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/LocalDataTransferServer.java
- rubix-core/src/main/java/com/qubole/rubix/core/NonLocalReadRequestChain.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/CacheConfig.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/DataTransferClientFactory.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/DataTransferClientHelper.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/RetryingPooledThriftClient.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPool.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/ObjectPoolPartition.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/PoolConfig.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/SocketChannelObjectFactory.java
- rubix-spi/src/main/java/com/qubole/rubix/spi/fop/SocketObjectFactory.java
- rubix-tests/src/test/java/com/qubole/rubix/tests/TestNonLocalReadRequestChain.java
- added Scavenger in connection pool to remove the long-unused connections from the pool.
- added connection pool for Local Data Transfer Server to keep persistent connections and reuse.
- added pool configs: socket timeout, connect timeout
> Changes to fix Local Data Transfer Server connectivity issues.

- rubix-client/src/main/java/com/qubole/rubix/metrics/BookKeeperMetricsClient.java
tested the script by running in a presto cluster.
> Add client for fetching bks metrics

- docs/contrib/issues.md
> Updated link to issues

- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/BookKeeper.java
> Cleanup cache directories before initializiing the cache

- rubix-bookkeeper/src/main/java/com/qubole/rubix/bookkeeper/FileMetadata.java
> Lowering log level of cache eviction

- rubix-spi/src/main/java/com/qubole/rubix/spi/ClusterManager.java
> Fix to update cluster nodes in consistent hash ring
